### ISSUE TITLE
Link to Google Chrome webstore gives 404

### ISSUE THREAD

**Issue by dsh2** [VastBlast/CustomAutoRefresh#3]
It seems, the extension was banned from the Google Chrome webstore. The link https://chrome.google.com/webstore/detail/hefmpdieencodgfnoecpichojkglajkb gives 404. 

Anyone knows what might have happened? Or what to do about it?

**Comment by awsms** [comment]
bump? @VastBlast

**Comment by VastBlast** [comment]
It was wrongfully taken down by Chrome, but it is now up again under a new listing. Updated the link in the readme.
